queries = [
{'keyword': 'hostel Ashok Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hotel Ashok Nagar in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Ashok Nagar in Kanpur', 'max_results': 200},
{'keyword': 'medical store Ashok Nagar in Kanpur', 'max_results': 200},
{'keyword': 'clinic Ashok Nagar in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Ashok Nagar in Kanpur', 'max_results': 200},
{'keyword': 'gym Ashok Nagar in Kanpur', 'max_results': 200},
{'keyword': 'park Ashok Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hostel Azad Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hotel Azad Nagar in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Azad Nagar in Kanpur', 'max_results': 200},
{'keyword': 'medical store Azad Nagar in Kanpur', 'max_results': 200},
{'keyword': 'clinic Azad Nagar in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Azad Nagar in Kanpur', 'max_results': 200},
{'keyword': 'gym Azad Nagar in Kanpur', 'max_results': 200},
{'keyword': 'park Azad Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hostel Bhauti in Kanpur', 'max_results': 200},
{'keyword': 'hotel Bhauti in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Bhauti in Kanpur', 'max_results': 200},
{'keyword': 'medical store Bhauti in Kanpur', 'max_results': 200},
{'keyword': 'clinic Bhauti in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Bhauti in Kanpur', 'max_results': 200},
{'keyword': 'gym Bhauti in Kanpur', 'max_results': 200},
{'keyword': 'park Bhauti in Kanpur', 'max_results': 200},
{'keyword': 'hostel Barra in Kanpur', 'max_results': 200},
{'keyword': 'hotel Barra in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Barra in Kanpur', 'max_results': 200},
{'keyword': 'medical store Barra in Kanpur', 'max_results': 200},
{'keyword': 'clinic Barra in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Barra in Kanpur', 'max_results': 200},
{'keyword': 'gym Barra in Kanpur', 'max_results': 200},
{'keyword': 'park Barra in Kanpur', 'max_results': 200},
{'keyword': 'hostel Civil Lines in Kanpur', 'max_results': 200},
{'keyword': 'hotel Civil Lines in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Civil Lines in Kanpur', 'max_results': 200},
{'keyword': 'medical store Civil Lines in Kanpur', 'max_results': 200},
{'keyword': 'clinic Civil Lines in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Civil Lines in Kanpur', 'max_results': 200},
{'keyword': 'gym Civil Lines in Kanpur', 'max_results': 200},
{'keyword': 'park Civil Lines in Kanpur', 'max_results': 200},
{'keyword': 'hostel Govind Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hotel Govind Nagar in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Govind Nagar in Kanpur', 'max_results': 200},
{'keyword': 'medical store Govind Nagar in Kanpur', 'max_results': 200},
{'keyword': 'clinic Govind Nagar in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Govind Nagar in Kanpur', 'max_results': 200},
{'keyword': 'gym Govind Nagar in Kanpur', 'max_results': 200},
{'keyword': 'park Govind Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hostel Kakadeo in Kanpur', 'max_results': 200},
{'keyword': 'hotel Kakadeo in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Kakadeo in Kanpur', 'max_results': 200},
{'keyword': 'medical store Kakadeo in Kanpur', 'max_results': 200},
{'keyword': 'clinic Kakadeo in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Kakadeo in Kanpur', 'max_results': 200},
{'keyword': 'gym Kakadeo in Kanpur', 'max_results': 200},
{'keyword': 'park Kakadeo in Kanpur', 'max_results': 200},
{'keyword': 'hostel Kalyanpur in Kanpur', 'max_results': 200},
{'keyword': 'hotel Kalyanpur in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Kalyanpur in Kanpur', 'max_results': 200},
{'keyword': 'medical store Kalyanpur in Kanpur', 'max_results': 200},
{'keyword': 'clinic Kalyanpur in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Kalyanpur in Kanpur', 'max_results': 200},
{'keyword': 'gym Kalyanpur in Kanpur', 'max_results': 200},
{'keyword': 'park Kalyanpur in Kanpur', 'max_results': 200},
{'keyword': 'hostel Kidwai Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hotel Kidwai Nagar in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Kidwai Nagar in Kanpur', 'max_results': 200},
{'keyword': 'medical store Kidwai Nagar in Kanpur', 'max_results': 200},
{'keyword': 'clinic Kidwai Nagar in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Kidwai Nagar in Kanpur', 'max_results': 200},
{'keyword': 'gym Kidwai Nagar in Kanpur', 'max_results': 200},
{'keyword': 'park Kidwai Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hostel Lajpat Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hotel Lajpat Nagar in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Lajpat Nagar in Kanpur', 'max_results': 200},
{'keyword': 'medical store Lajpat Nagar in Kanpur', 'max_results': 200},
{'keyword': 'clinic Lajpat Nagar in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Lajpat Nagar in Kanpur', 'max_results': 200},
{'keyword': 'gym Lajpat Nagar in Kanpur', 'max_results': 200},
{'keyword': 'park Lajpat Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hostel Mall Road in Kanpur', 'max_results': 200},
{'keyword': 'hotel Mall Road in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Mall Road in Kanpur', 'max_results': 200},
{'keyword': 'medical store Mall Road in Kanpur', 'max_results': 200},
{'keyword': 'clinic Mall Road in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Mall Road in Kanpur', 'max_results': 200},
{'keyword': 'gym Mall Road in Kanpur', 'max_results': 200},
{'keyword': 'park Mall Road in Kanpur', 'max_results': 200},
{'keyword': 'hostel Naubasta in Kanpur', 'max_results': 200},
{'keyword': 'hotel Naubasta in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Naubasta in Kanpur', 'max_results': 200},
{'keyword': 'medical store Naubasta in Kanpur', 'max_results': 200},
{'keyword': 'clinic Naubasta in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Naubasta in Kanpur', 'max_results': 200},
{'keyword': 'gym Naubasta in Kanpur', 'max_results': 200},
{'keyword': 'park Naubasta in Kanpur', 'max_results': 200},
{'keyword': 'hostel Panki in Kanpur', 'max_results': 200},
{'keyword': 'hotel Panki in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Panki in Kanpur', 'max_results': 200},
{'keyword': 'medical store Panki in Kanpur', 'max_results': 200},
{'keyword': 'clinic Panki in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Panki in Kanpur', 'max_results': 200},
{'keyword': 'gym Panki in Kanpur', 'max_results': 200},
{'keyword': 'park Panki in Kanpur', 'max_results': 200},
{'keyword': 'hostel Pandu Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hotel Pandu Nagar in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Pandu Nagar in Kanpur', 'max_results': 200},
{'keyword': 'medical store Pandu Nagar in Kanpur', 'max_results': 200},
{'keyword': 'clinic Pandu Nagar in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Pandu Nagar in Kanpur', 'max_results': 200},
{'keyword': 'gym Pandu Nagar in Kanpur', 'max_results': 200},
{'keyword': 'park Pandu Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hostel Swaroop Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hotel Swaroop Nagar in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Swaroop Nagar in Kanpur', 'max_results': 200},
{'keyword': 'medical store Swaroop Nagar in Kanpur', 'max_results': 200},
{'keyword': 'clinic Swaroop Nagar in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Swaroop Nagar in Kanpur', 'max_results': 200},
{'keyword': 'gym Swaroop Nagar in Kanpur', 'max_results': 200},
{'keyword': 'park Swaroop Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hostel Shastri Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hotel Shastri Nagar in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Shastri Nagar in Kanpur', 'max_results': 200},
{'keyword': 'medical store Shastri Nagar in Kanpur', 'max_results': 200},
{'keyword': 'clinic Shastri Nagar in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Shastri Nagar in Kanpur', 'max_results': 200},
{'keyword': 'gym Shastri Nagar in Kanpur', 'max_results': 200},
{'keyword': 'park Shastri Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hostel Gomti Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hotel Gomti Nagar in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Gomti Nagar in Kanpur', 'max_results': 200},
{'keyword': 'medical store Gomti Nagar in Kanpur', 'max_results': 200},
{'keyword': 'clinic Gomti Nagar in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Gomti Nagar in Kanpur', 'max_results': 200},
{'keyword': 'gym Gomti Nagar in Kanpur', 'max_results': 200},
{'keyword': 'park Gomti Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hostel Saket Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hotel Saket Nagar in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Saket Nagar in Kanpur', 'max_results': 200},
{'keyword': 'medical store Saket Nagar in Kanpur', 'max_results': 200},
{'keyword': 'clinic Saket Nagar in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Saket Nagar in Kanpur', 'max_results': 200},
{'keyword': 'gym Saket Nagar in Kanpur', 'max_results': 200},
{'keyword': 'park Saket Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hostel Tilak Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hotel Tilak Nagar in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Tilak Nagar in Kanpur', 'max_results': 200},
{'keyword': 'medical store Tilak Nagar in Kanpur', 'max_results': 200},
{'keyword': 'clinic Tilak Nagar in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Tilak Nagar in Kanpur', 'max_results': 200},
{'keyword': 'gym Tilak Nagar in Kanpur', 'max_results': 200},
{'keyword': 'park Tilak Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hostel Yashoda Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hotel Yashoda Nagar in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Yashoda Nagar in Kanpur', 'max_results': 200},
{'keyword': 'medical store Yashoda Nagar in Kanpur', 'max_results': 200},
{'keyword': 'clinic Yashoda Nagar in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Yashoda Nagar in Kanpur', 'max_results': 200},
{'keyword': 'gym Yashoda Nagar in Kanpur', 'max_results': 200},
{'keyword': 'park Yashoda Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hostel Fazalganj in Kanpur', 'max_results': 200},
{'keyword': 'hotel Fazalganj in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Fazalganj in Kanpur', 'max_results': 200},
{'keyword': 'medical store Fazalganj in Kanpur', 'max_results': 200},
{'keyword': 'clinic Fazalganj in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Fazalganj in Kanpur', 'max_results': 200},
{'keyword': 'gym Fazalganj in Kanpur', 'max_results': 200},
{'keyword': 'park Fazalganj in Kanpur', 'max_results': 200},
{'keyword': 'hostel Indira Nagar in Kanpur', 'max_results': 200},
{'keyword': 'hotel Indira Nagar in Kanpur', 'max_results': 200},
{'keyword': 'tiffin service Indira Nagar in Kanpur', 'max_results': 200},
{'keyword': 'medical store Indira Nagar in Kanpur', 'max_results': 200},
{'keyword': 'clinic Indira Nagar in Kanpur', 'max_results': 200},
{'keyword': 'restaurant Indira Nagar in Kanpur', 'max_results': 200},
{'keyword': 'gym Indira Nagar in Kanpur', 'max_results': 200},
{'keyword': 'park Indira Nagar in Kanpur', 'max_results': 200},
]

number_of_scrapers=9